#############################
#		STATIC EXAMPLE		#
#############################

server {
	listen localhost:8081 default_server;
	root data/42sp/;
	autoindex on;
	location / {
		methods GET;
	}
}

server {
	listen localhost:8081 default_server;
	root data/42sp/;
	autoindex on;
	location / {
		methods GET;
	}
}