#############################
#		STATIC EXAMPLE		#
#############################

server {
	listen 127.0.0.1:8092;

	location / {
		methods GET;
		return 200 HelloWorld;
	}
}
#############################
#		STATIC EXAMPLE		#
#############################

server {
	listen 127.0.0.1:8090;

	location / {
		methods GET;
		return 200 HelloWorld;
	}
}
#############################
#		STATIC EXAMPLE		#
#############################

server {
	listen 127.0.0.1:8086;

	location / {
		methods GET;
		return 200 HelloWorld;
	}
}