server {
    listen 8080;
    server_name localhost;
    root /home/shiro/GitHub/webserv/data/login;

    location / {
        index index.html index.php;
        methods GET POST;
        cgi .php /usr/bin/php-cgi;
    }
}