# MAIN SERVER
server {
    listen 8080;
    server_name localhost;
    root /home/shiro/GitHub/webserv/data/php_server;

    location / {
        index index.html index.php;
        methods GET POST;
        cgi .php /usr/bin/php-cgi;
    }

    location /login {
        return 302 http://localhost:8081/login;
    }

    location /login.php {
        return 302 http://localhost:8081/login;
    }

    location /register {
        return 302 http://localhost:8081/register;
    }

    location /register.php {
        return 302 http://localhost:8081/register;
    }
}

# LOGIN AND REGISTER
server {
    listen 8081;
    server_name localhost;
    root /home/shiro/GitHub/webserv/data/php_server;
    
    location / {
        return 301 http://localhost:8080/;
    }

    location /login.php {
        return 301 /login;
    }

    location /register.php {
        return 301 /register;
    }

    location /login {
        index login.php;
        methods GET POST;
        cgi .php /usr/bin/php-cgi;
    }
    
    location /register {
        index register.php;
        methods GET POST;
        cgi .php /usr/bin/php-cgi;
    }

    location /favicon.ico {
        methods GET;
    }
}