#############################
#		STATIC EXAMPLE		#
#############################

server {
	listen 127.0.0.1:8092;

	server_name example.com www.example.com;
	location / {
		methods GET;
		return 200 HelloWorld;
	}
}
#############################
#		STATIC EXAMPLE		#
#############################

server {
	listen 127.0.0.1:8092 default_server;

	server_name example.com www.example2.com;
	location / {
		methods GET;
		return 200 HelloWorld;
	}
}
#############################
#		STATIC EXAMPLE		#
#############################

server {
	listen 127.0.0.1:8086;
	listen 127.0.0.5:8080 default_server;

	location / {
		methods GET;
		return 200 HelloWorld;
	}
}

server {
	listen 127.0.0.1:8086;
	listen 127.0.0.5:8080 default_server;

	location / {
		methods GET;
		return 200 HelloWorld;
	}
}

server {
	listen 127.0.0.1:8086;
	listen 127.0.0.5:8080 default_server;
	location / {
		methods GET;
		return 200 HelloWorld;
	}
}